(function () {
    // 1. 현재 사이트의 도메인 추출 (예: .youtube.com)
    let domain = window.location.hostname;
    if (!domain.startsWith('.')) {
        domain = '.' + domain;
    }

    // 2. Netscape 헤더 추가
    let output = "# Netscape HTTP Cookie File\n# This file is automatically generated by JS\n\n";

    // 밑의 문자열에 쿠키를 입력
    const ck = '';

    // 3. document.cookie 문자열을 파싱하여 Netscape 포맷으로 변환
    ck.split(';').forEach(cookie => {
        let trimmed = cookie.trim();
        if (!trimmed) return;

        let eqIndex = trimmed.indexOf('=');
        if (eqIndex === -1) return;

        let name = trimmed.substring(0, eqIndex);
        let value = trimmed.substring(eqIndex + 1);

        // 만료시간(기본값 10년 뒤 만료 숫자로 임의 세팅)
        let expiry = Math.floor(Date.now() / 1000) + (3650 * 24 * 60 * 60);

        // Netscape 표준 형식: 도메인 / 하위도메인여부 / 경로 / 보안여부 / 만료시간 / 이름 / 값
        output += `${domain}\tTRUE\t/\tFALSE\t${expiry}\t${name}\t${value}\n`;
    });

    // 4. 콘솔창에 출력 및 클립보드 복사 안내
    console.log(output);
    copy(output);
    alert("쿠키가 클립보드에 복사되었습니다! 메모장에 붙여넣기(Ctrl+V) 하세요.");
})();